name: Github Context
on: 
 push:
  branches: 
    - main
    - 'dev-*'
    - 'feature/*'
 pull_request: 
  types:
    - opened
    - edited
    - closed
 workflow_dispatch:
jobs:
 context-job:
       runs-on: ubuntu-latest
       steps:
       - name: Output GithHub context
         run: echo "${{ toJSON(Github) }}"
       
