name: Sample Workflow

on:
  workflow_dispatch:

jobs:
  TestJob:
    runs-on: ubuntu-latest

    steps:
      - name: Print the greeting
        run: echo "Sample Workflow"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with: 
             version: 21
      - name: install dependencies
        run: npm ci
      - name: About Repo
      - run: echo "${{ toJson (github) }}"
    
        
     
        
        


      
