name: Test and deploy pipeline.
on: 
 workflow_dispatch:
jobs:
 Test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with: 
            node-version: 24
      - name: Install node js dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
   
