name: UploadAndDownload
on: 
 workflow_dispatch:
jobs:
 uploadAnddownload-Artifacts:
    runs-on: ubuntu-latest
    steps:
     - name: List src contents
       run: ls -R src
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: API Service
         path: |
                src/api-service
                src/App.jsx

     - name: Download Artifact
       uses: actions/download-artifact@v4.3.0
       with: 
        name: API Service

     
       
   
